version: "3.8"

services:
        plane-web:
                container_name: planefrontend
                image: makeplane/plane-frontend:latest
                restart: always
                command: /usr/local/bin/start.sh

        plane-api:
                container_name: planebackend
                image: makeplane/plane-backend:latest
                restart: always
                command: ./bin/takeoff
                depends_on:
                        - plane-db
                        - plane-redis

        plane-worker:
                container_name: planerqworker
                image: makeplane/plane-worker:latest
                restart: always
                command: ./bin/worker
                depends_on:
                        - plane-api
                        - plane-db
                        - plane-redis

        plane-db:
                container_name: plane-db
                image: postgres:15.2-alpine
                restart: always
                command: postgres -c 'max_connections=1000'
                volumes:
                        - pgdata:/var/lib/postgresql/data

        plane-redis:
                container_name: plane-redis
                image: redis:6.2.7-alpine
                restart: always
                volumes:
                        - redisdata:/data

        plane-minio:
                container_name: plane-minio
                image: minio/minio
                volumes:
                        - uploads:/export
                environment:
                        MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
                        MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
                command: server /export --console-address ":9090"
        createbuckets:
                image: minio/mc
                depends_on:
                  - plane-minio
                entrypoint: >
                  /bin/sh -c "
                  /usr/bin/mc config host add plane-minio http://plane-minio:9000 \$AWS_ACCESS_KEY_ID \$AWS_SECRET_ACCESS_KEY;
                  /usr/bin/mc mb plane-minio/\$AWS_S3_BUCKET_NAME;
                  /usr/bin/mc anonymous set download plane-minio/\$AWS_S3_BUCKET_NAME;
                  exit 0;
                  "
volumes:
        pgdata:
        redisdata:
        uploads:
